### ISSUE TITLE
Implement the ability to check is panel currently visible.

### ISSUE THREAD

**Issue by eliogrin** [Invictum/invictum-test#20]
It will be great if we will provide possibility to check visibility of panel. So user can do some asserts, for example.

**Comment by Invictum** [comment]
@eliogrin 
With current architecture panel object is initialised immediately in getPanel() method. If it not present ElementNotFoundException will be thrown. It is possible to init invisible panel (it should be present in DOM, but not displayed via CSS).
So what behaviour do you expect? And how check visibility of Floating panels?

**Comment by eliogrin** [comment]
For example search suggestion, which one loaded with ajax, so it's not in the DOM when the page is load.
So I would like something like that:

```
searchSteps.enterSearch("test");
assertThat("Suggest didn't loaded after putting query.", searchSteps.isSuggestVisible();, equalTo(true));
searchSteps.cleanSearch();
assertThat("Suggest shouldn't be visible after clean query.", searchSteps.isSuggestVisible();, equalTo(false));
```

And implementation of .isSugestVisible():

```
public void isSuggestVisible() {
    return getPanel(SuggestPanel.class).isVisible();
}
```

So, I believe that you should try/catch ElementNotFoundException, and return false in this case.

**Comment by Invictum** [comment]
To work with panel you should init it with getPanel. With current implementation you will get ElementNotFoundException on init stage and isVisible method is inaccsesible

**Comment by eliogrin** [comment]
Yes, this why I create request for this functionality. I have no solution right now, but still I hope this will pretty useful functionality if we found how to implement it.

**Comment by Invictum** [comment]
Implemented.
