### ISSUE TITLE
Ability to define iframe as panel

### ISSUE THREAD

**Issue by Invictum** [Invictum/invictum-test#4]
It is possible to build proxy around Frame Panels and provide switching during method interception.
Java cglib allows to do it via byte code manipulation.

**Comment by eliogrin** [comment]
@Invictum you would like to have same names as panels, or probably something different? Can you describe more informative?

**Comment by Invictum** [comment]
Actually I had an investigation related to this task and there is no way to implement it without aspectJ approach. It is not a accseptale so issue could be closed.

**Comment by Invictum** [comment]
Implemented. Will be available in version 1.5
Documentation update is needed
